import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

// eslint-disable-next-line no-console

// Get __dirname equivalent in ES modules
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Copy gameConstants.js from src/shared to src/public/js/modules
const gameConstantsSourcePath = path.join(
  __dirname,
  '../src/shared/gameConstants.js'
);
const gameConstantsDestPath = path.join(
  __dirname,
  '../src/public/js/modules/gameConstants.js'
);

// Copy sharedGameUtils.js from src/shared to src/public/js/modules as sharedGameUtils.js
const gameUtilsSourcePath = path.join(
  __dirname,
  '../src/shared/sharedGameUtils.js'
);
const gameUtilsDestPath = path.join(
  __dirname,
  '../src/public/js/modules/sharedGameUtils.js'
);

try {
  // Copy gameConstants.js
  const gameConstants = fs.readFileSync(gameConstantsSourcePath, 'utf8');
  const gameConstantsHeader = `// ============================================================================
// GENERATED FILE - DO NOT EDIT DIRECTLY
// This file is automatically generated and will be overwritten
// ============================================================================

`;
  fs.writeFileSync(gameConstantsDestPath, gameConstantsHeader + gameConstants);
  // eslint-disable-next-line no-console
  console.log('✅ gameConstants.js copied successfully');
} catch (error) {
  // eslint-disable-next-line no-console
  console.error('❌ Error copying gameConstants.js:', error.message);
}

try {
  // Copy gameUtils.js
  const gameUtils = fs.readFileSync(gameUtilsSourcePath, 'utf8');
  const gameUtilsHeader = `// ============================================================================
// GENERATED FILE - DO NOT EDIT DIRECTLY
// This file is automatically generated and will be overwritten
// ============================================================================

`;
  fs.writeFileSync(gameUtilsDestPath, gameUtilsHeader + gameUtils);
  // eslint-disable-next-line no-console
  console.log('✅ sharedGameUtils.js copied successfully');
} catch (error) {
  // eslint-disable-next-line no-console
  console.error('❌ Error copying sharedGameUtils.js:', error.message);
}
